apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: moves-like-swagger
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
  steps:
  - image: ghcr.io/jenkins-x/jx-promote:0.0.234
    name: promote-jx-preview
    resources: {}
    script: |
      #!/usr/bin/env sh
      source /workspace/source/.jx/variables.sh
      jx promote -b --all-auto --timeout 1h --no-poll
      echo $VERSION > package_version
    workingDir: /workspace/source
  - image: craggs/openapi-angular-builder
    name: moves-like-swagger
    resources: {}
    script: |
      #!/usr/bin/env sh
      . .jx/variables.sh
      . swagger-gen-variables.sh
      cd ./registry
      /CreateAngularPackageV2.sh $SWAGGERURL $(cat package_version)
    workingDir: /workspace/source
  workspaces:
  - description: Swagger generation will occur on the staging url once it has been built.
    mountPath: /workspace
    name: output