apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: moves-like-swagger
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
  steps:
  - image: craggs/openapi-angular-builder
    name: moves-like-swagger
    resources: {}
    script: |
      #!/usr/bin/env sh
      source /workspace/source/.jx/variables.sh
      echo name $SwaggerServiceName
      echo version $version
      cd ./registry
      /CreateAngularPackageV2.sh https://api-staging.jx.mqube.build/swagger/docs/v1/$SwaggerServiceName $VERSION
    workingDir: /workspace/source
  workspaces:
  - description: Swagger generation will occur on the staging url once it has been built.
    mountPath: /workspace
    name: output