apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: git-clone-pr
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
  steps:
  - image: ghcr.io/jenkins-x/jx-promote:0.0.234
    name: promote-jx-preview
    resources: {}
    script: |
      #!/usr/bin/env sh
      source /workspace/source/.jx/variables.sh
      jx secret copy --create-namespace --selector "secret.jenkins-x.io/replica-source=true" -n preview-secrets --to jx-$REPO_OWNER-$APP_NAME-pr-$PULL_NUMBER
      jx preview create
      echo $(kubectl get services -A | grep jx-$REPO_OWNER-$APP_NAME-pr-$PULL_NUMBER | awk '$2 == "'$APP_NAME'" {print $4}')
      echo $(kubectl get services -A | grep jx-$REPO_OWNER-$APP_NAME-pr-$PULL_NUMBER | awk '$2 == "'$APP_NAME'" {print $4}') > pod_ip
      echo "0.0.$PULL_NUMBER-rc.$BUILD_ID"
      echo "0.0.$PULL_NUMBER-rc.$BUILD_ID" > package_version
      ls
    workingDir: /workspace/source
  - image: craggs/openapi-angular-builder
    name: moves-like-swagger
    resources: {}
    script: |
        #!/usr/bin/env sh
        ls
        source .jx/variables.sh
        source  swagger-gen-variables.sh
        export POD_IP=$(cat pod_ip)
        export PACKAGE_VERSION=$(cat package_version)
        cd ./registry
        /CreateAngularPackageV2.sh http://$POD_IP:5000/swagger/v1/swagger.json $PACKAGE_VERSION
    workingDir: /workspace
  workspaces:
  - description: The git repo will be cloned onto the volume backing this workspace
    mountPath: /workspace
    name: output